# Generated by Django 4.2.16 on 2026-06-08 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontask',
            name='rectification_deadline_days',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='RectificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('rectification_deadline', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rectifications', to='core.reviewrecord')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rectifications', to='core.inspectiontask')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
    ]
